//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.31 at 01:54:09 AM CST 
//


package com.nittodigital.webservice.models.soap.production;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.nittodigital.webservice.models.soap.production package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.nittodigital.webservice.models.soap.production
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetProductionRequest }
     * 
     */
    public GetProductionRequest createGetProductionRequest() {
        return new GetProductionRequest();
    }

    /**
     * Create an instance of {@link GetProductionResponse }
     * 
     */
    public GetProductionResponse createGetProductionResponse() {
        return new GetProductionResponse();
    }

    /**
     * Create an instance of {@link Production }
     * 
     */
    public Production createProduction() {
        return new Production();
    }

}
